# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1ContainerStateRunning(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, started_at: IoK8sApimachineryPkgApisMetaV1Time=None):  # noqa: E501
        """IoK8sApiCoreV1ContainerStateRunning - a model defined in Swagger

        :param started_at: The started_at of this IoK8sApiCoreV1ContainerStateRunning.  # noqa: E501
        :type started_at: IoK8sApimachineryPkgApisMetaV1Time
        """
        self.swagger_types = {
            'started_at': IoK8sApimachineryPkgApisMetaV1Time
        }

        self.attribute_map = {
            'started_at': 'startedAt'
        }

        self._started_at = started_at

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1ContainerStateRunning':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.ContainerStateRunning of this IoK8sApiCoreV1ContainerStateRunning.  # noqa: E501
        :rtype: IoK8sApiCoreV1ContainerStateRunning
        """
        return util.deserialize_model(dikt, cls)

    @property
    def started_at(self) -> IoK8sApimachineryPkgApisMetaV1Time:
        """Gets the started_at of this IoK8sApiCoreV1ContainerStateRunning.

        Time at which the container was last (re-)started  # noqa: E501

        :return: The started_at of this IoK8sApiCoreV1ContainerStateRunning.
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at: IoK8sApimachineryPkgApisMetaV1Time):
        """Sets the started_at of this IoK8sApiCoreV1ContainerStateRunning.

        Time at which the container was last (re-)started  # noqa: E501

        :param started_at: The started_at of this IoK8sApiCoreV1ContainerStateRunning.
        :type started_at: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._started_at = started_at
