# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, last_update_time: IoK8sApimachineryPkgApisMetaV1Time=None, message: str=None, reason: str=None, type: str=None):  # noqa: E501
        """IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition - a model defined in Swagger

        :param last_update_time: The last_update_time of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.  # noqa: E501
        :type last_update_time: IoK8sApimachineryPkgApisMetaV1Time
        :param message: The message of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.  # noqa: E501
        :type message: str
        :param reason: The reason of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.  # noqa: E501
        :type reason: str
        :param type: The type of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'last_update_time': IoK8sApimachineryPkgApisMetaV1Time,
            'message': str,
            'reason': str,
            'type': str
        }

        self.attribute_map = {
            'last_update_time': 'lastUpdateTime',
            'message': 'message',
            'reason': 'reason',
            'type': 'type'
        }

        self._last_update_time = last_update_time
        self._message = message
        self._reason = reason
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.certificates.v1beta1.CertificateSigningRequestCondition of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.  # noqa: E501
        :rtype: IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def last_update_time(self) -> IoK8sApimachineryPkgApisMetaV1Time:
        """Gets the last_update_time of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        timestamp for the last update to this condition  # noqa: E501

        :return: The last_update_time of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._last_update_time

    @last_update_time.setter
    def last_update_time(self, last_update_time: IoK8sApimachineryPkgApisMetaV1Time):
        """Sets the last_update_time of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        timestamp for the last update to this condition  # noqa: E501

        :param last_update_time: The last_update_time of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :type last_update_time: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._last_update_time = last_update_time

    @property
    def message(self) -> str:
        """Gets the message of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        human readable message with details about the request state  # noqa: E501

        :return: The message of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        human readable message with details about the request state  # noqa: E501

        :param message: The message of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :type message: str
        """

        self._message = message

    @property
    def reason(self) -> str:
        """Gets the reason of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        brief reason for the request state  # noqa: E501

        :return: The reason of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        brief reason for the request state  # noqa: E501

        :param reason: The reason of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :type reason: str
        """

        self._reason = reason

    @property
    def type(self) -> str:
        """Gets the type of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        request approval state, currently Approved or Denied.  # noqa: E501

        :return: The type of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.

        request approval state, currently Approved or Denied.  # noqa: E501

        :param type: The type of this IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
