# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1PodTemplateSpec(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta=None, spec: IoK8sApiCoreV1PodSpec=None):  # noqa: E501
        """IoK8sApiCoreV1PodTemplateSpec - a model defined in Swagger

        :param metadata: The metadata of this IoK8sApiCoreV1PodTemplateSpec.  # noqa: E501
        :type metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        :param spec: The spec of this IoK8sApiCoreV1PodTemplateSpec.  # noqa: E501
        :type spec: IoK8sApiCoreV1PodSpec
        """
        self.swagger_types = {
            'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMeta,
            'spec': IoK8sApiCoreV1PodSpec
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'spec': 'spec'
        }

        self._metadata = metadata
        self._spec = spec

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1PodTemplateSpec':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.PodTemplateSpec of this IoK8sApiCoreV1PodTemplateSpec.  # noqa: E501
        :rtype: IoK8sApiCoreV1PodTemplateSpec
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> IoK8sApimachineryPkgApisMetaV1ObjectMeta:
        """Gets the metadata of this IoK8sApiCoreV1PodTemplateSpec.

        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata  # noqa: E501

        :return: The metadata of this IoK8sApiCoreV1PodTemplateSpec.
        :rtype: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta):
        """Sets the metadata of this IoK8sApiCoreV1PodTemplateSpec.

        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata  # noqa: E501

        :param metadata: The metadata of this IoK8sApiCoreV1PodTemplateSpec.
        :type metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """

        self._metadata = metadata

    @property
    def spec(self) -> IoK8sApiCoreV1PodSpec:
        """Gets the spec of this IoK8sApiCoreV1PodTemplateSpec.

        Specification of the desired behavior of the pod. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status  # noqa: E501

        :return: The spec of this IoK8sApiCoreV1PodTemplateSpec.
        :rtype: IoK8sApiCoreV1PodSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec: IoK8sApiCoreV1PodSpec):
        """Sets the spec of this IoK8sApiCoreV1PodTemplateSpec.

        Specification of the desired behavior of the pod. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status  # noqa: E501

        :param spec: The spec of this IoK8sApiCoreV1PodTemplateSpec.
        :type spec: IoK8sApiCoreV1PodSpec
        """

        self._spec = spec
