# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, format: str=None, json_path: str=None, name: str=None, priority: int=None, type: str=None):  # noqa: E501
        """IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition - a model defined in Swagger

        :param description: The description of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :type description: str
        :param format: The format of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :type format: str
        :param json_path: The json_path of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :type json_path: str
        :param name: The name of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :type name: str
        :param priority: The priority of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :type priority: int
        :param type: The type of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'description': str,
            'format': str,
            'json_path': str,
            'name': str,
            'priority': int,
            'type': str
        }

        self.attribute_map = {
            'description': 'description',
            'format': 'format',
            'json_path': 'jsonPath',
            'name': 'name',
            'priority': 'priority',
            'type': 'type'
        }

        self._description = description
        self._format = format
        self._json_path = json_path
        self._name = name
        self._priority = priority
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.  # noqa: E501
        :rtype: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        description is a human readable description of this column.  # noqa: E501

        :return: The description of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        description is a human readable description of this column.  # noqa: E501

        :param description: The description of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :type description: str
        """

        self._description = description

    @property
    def format(self) -> str:
        """Gets the format of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        format is an optional OpenAPI type definition for this column. The 'name' format is applied to the primary identifier column to assist in clients identifying column is the resource name. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.  # noqa: E501

        :return: The format of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        format is an optional OpenAPI type definition for this column. The 'name' format is applied to the primary identifier column to assist in clients identifying column is the resource name. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.  # noqa: E501

        :param format: The format of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :type format: str
        """

        self._format = format

    @property
    def json_path(self) -> str:
        """Gets the json_path of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        jsonPath is a simple JSON path (i.e. with array notation) which is evaluated against each custom resource to produce the value for this column.  # noqa: E501

        :return: The json_path of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :rtype: str
        """
        return self._json_path

    @json_path.setter
    def json_path(self, json_path: str):
        """Sets the json_path of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        jsonPath is a simple JSON path (i.e. with array notation) which is evaluated against each custom resource to produce the value for this column.  # noqa: E501

        :param json_path: The json_path of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :type json_path: str
        """
        if json_path is None:
            raise ValueError("Invalid value for `json_path`, must not be `None`")  # noqa: E501

        self._json_path = json_path

    @property
    def name(self) -> str:
        """Gets the name of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        name is a human readable name for the column.  # noqa: E501

        :return: The name of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        name is a human readable name for the column.  # noqa: E501

        :param name: The name of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def priority(self) -> int:
        """Gets the priority of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        priority is an integer defining the relative importance of this column compared to others. Lower numbers are considered higher priority. Columns that may be omitted in limited space scenarios should be given a priority greater than 0.  # noqa: E501

        :return: The priority of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        priority is an integer defining the relative importance of this column compared to others. Lower numbers are considered higher priority. Columns that may be omitted in limited space scenarios should be given a priority greater than 0.  # noqa: E501

        :param priority: The priority of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :type priority: int
        """

        self._priority = priority

    @property
    def type(self) -> str:
        """Gets the type of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        type is an OpenAPI type definition for this column. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.  # noqa: E501

        :return: The type of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.

        type is an OpenAPI type definition for this column. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.  # noqa: E501

        :param type: The type of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
