# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiPolicyV1beta1Eviction(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, api_version: str=None, delete_options: IoK8sApimachineryPkgApisMetaV1DeleteOptions=None, kind: str=None, metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta=None):  # noqa: E501
        """IoK8sApiPolicyV1beta1Eviction - a model defined in Swagger

        :param api_version: The api_version of this IoK8sApiPolicyV1beta1Eviction.  # noqa: E501
        :type api_version: str
        :param delete_options: The delete_options of this IoK8sApiPolicyV1beta1Eviction.  # noqa: E501
        :type delete_options: IoK8sApimachineryPkgApisMetaV1DeleteOptions
        :param kind: The kind of this IoK8sApiPolicyV1beta1Eviction.  # noqa: E501
        :type kind: str
        :param metadata: The metadata of this IoK8sApiPolicyV1beta1Eviction.  # noqa: E501
        :type metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """
        self.swagger_types = {
            'api_version': str,
            'delete_options': IoK8sApimachineryPkgApisMetaV1DeleteOptions,
            'kind': str,
            'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMeta
        }

        self.attribute_map = {
            'api_version': 'apiVersion',
            'delete_options': 'deleteOptions',
            'kind': 'kind',
            'metadata': 'metadata'
        }

        self._api_version = api_version
        self._delete_options = delete_options
        self._kind = kind
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiPolicyV1beta1Eviction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.policy.v1beta1.Eviction of this IoK8sApiPolicyV1beta1Eviction.  # noqa: E501
        :rtype: IoK8sApiPolicyV1beta1Eviction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_version(self) -> str:
        """Gets the api_version of this IoK8sApiPolicyV1beta1Eviction.

        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources  # noqa: E501

        :return: The api_version of this IoK8sApiPolicyV1beta1Eviction.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this IoK8sApiPolicyV1beta1Eviction.

        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources  # noqa: E501

        :param api_version: The api_version of this IoK8sApiPolicyV1beta1Eviction.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def delete_options(self) -> IoK8sApimachineryPkgApisMetaV1DeleteOptions:
        """Gets the delete_options of this IoK8sApiPolicyV1beta1Eviction.

        DeleteOptions may be provided  # noqa: E501

        :return: The delete_options of this IoK8sApiPolicyV1beta1Eviction.
        :rtype: IoK8sApimachineryPkgApisMetaV1DeleteOptions
        """
        return self._delete_options

    @delete_options.setter
    def delete_options(self, delete_options: IoK8sApimachineryPkgApisMetaV1DeleteOptions):
        """Sets the delete_options of this IoK8sApiPolicyV1beta1Eviction.

        DeleteOptions may be provided  # noqa: E501

        :param delete_options: The delete_options of this IoK8sApiPolicyV1beta1Eviction.
        :type delete_options: IoK8sApimachineryPkgApisMetaV1DeleteOptions
        """

        self._delete_options = delete_options

    @property
    def kind(self) -> str:
        """Gets the kind of this IoK8sApiPolicyV1beta1Eviction.

        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds  # noqa: E501

        :return: The kind of this IoK8sApiPolicyV1beta1Eviction.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this IoK8sApiPolicyV1beta1Eviction.

        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds  # noqa: E501

        :param kind: The kind of this IoK8sApiPolicyV1beta1Eviction.
        :type kind: str
        """

        self._kind = kind

    @property
    def metadata(self) -> IoK8sApimachineryPkgApisMetaV1ObjectMeta:
        """Gets the metadata of this IoK8sApiPolicyV1beta1Eviction.

        ObjectMeta describes the pod that is being evicted.  # noqa: E501

        :return: The metadata of this IoK8sApiPolicyV1beta1Eviction.
        :rtype: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta):
        """Sets the metadata of this IoK8sApiPolicyV1beta1Eviction.

        ObjectMeta describes the pod that is being evicted.  # noqa: E501

        :param metadata: The metadata of this IoK8sApiPolicyV1beta1Eviction.
        :type metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """

        self._metadata = metadata
