# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiAutoscalingV2beta1MetricSpec(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, external: IoK8sApiAutoscalingV2beta1ExternalMetricSource=None, object: IoK8sApiAutoscalingV2beta1ObjectMetricSource=None, pods: IoK8sApiAutoscalingV2beta1PodsMetricSource=None, resource: IoK8sApiAutoscalingV2beta1ResourceMetricSource=None, type: str=None):  # noqa: E501
        """IoK8sApiAutoscalingV2beta1MetricSpec - a model defined in Swagger

        :param external: The external of this IoK8sApiAutoscalingV2beta1MetricSpec.  # noqa: E501
        :type external: IoK8sApiAutoscalingV2beta1ExternalMetricSource
        :param object: The object of this IoK8sApiAutoscalingV2beta1MetricSpec.  # noqa: E501
        :type object: IoK8sApiAutoscalingV2beta1ObjectMetricSource
        :param pods: The pods of this IoK8sApiAutoscalingV2beta1MetricSpec.  # noqa: E501
        :type pods: IoK8sApiAutoscalingV2beta1PodsMetricSource
        :param resource: The resource of this IoK8sApiAutoscalingV2beta1MetricSpec.  # noqa: E501
        :type resource: IoK8sApiAutoscalingV2beta1ResourceMetricSource
        :param type: The type of this IoK8sApiAutoscalingV2beta1MetricSpec.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'external': IoK8sApiAutoscalingV2beta1ExternalMetricSource,
            'object': IoK8sApiAutoscalingV2beta1ObjectMetricSource,
            'pods': IoK8sApiAutoscalingV2beta1PodsMetricSource,
            'resource': IoK8sApiAutoscalingV2beta1ResourceMetricSource,
            'type': str
        }

        self.attribute_map = {
            'external': 'external',
            'object': 'object',
            'pods': 'pods',
            'resource': 'resource',
            'type': 'type'
        }

        self._external = external
        self._object = object
        self._pods = pods
        self._resource = resource
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiAutoscalingV2beta1MetricSpec':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.autoscaling.v2beta1.MetricSpec of this IoK8sApiAutoscalingV2beta1MetricSpec.  # noqa: E501
        :rtype: IoK8sApiAutoscalingV2beta1MetricSpec
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external(self) -> IoK8sApiAutoscalingV2beta1ExternalMetricSource:
        """Gets the external of this IoK8sApiAutoscalingV2beta1MetricSpec.

        external refers to a global metric that is not associated with any Kubernetes object. It allows autoscaling based on information coming from components running outside of cluster (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).  # noqa: E501

        :return: The external of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :rtype: IoK8sApiAutoscalingV2beta1ExternalMetricSource
        """
        return self._external

    @external.setter
    def external(self, external: IoK8sApiAutoscalingV2beta1ExternalMetricSource):
        """Sets the external of this IoK8sApiAutoscalingV2beta1MetricSpec.

        external refers to a global metric that is not associated with any Kubernetes object. It allows autoscaling based on information coming from components running outside of cluster (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).  # noqa: E501

        :param external: The external of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :type external: IoK8sApiAutoscalingV2beta1ExternalMetricSource
        """

        self._external = external

    @property
    def object(self) -> IoK8sApiAutoscalingV2beta1ObjectMetricSource:
        """Gets the object of this IoK8sApiAutoscalingV2beta1MetricSpec.

        object refers to a metric describing a single kubernetes object (for example, hits-per-second on an Ingress object).  # noqa: E501

        :return: The object of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :rtype: IoK8sApiAutoscalingV2beta1ObjectMetricSource
        """
        return self._object

    @object.setter
    def object(self, object: IoK8sApiAutoscalingV2beta1ObjectMetricSource):
        """Sets the object of this IoK8sApiAutoscalingV2beta1MetricSpec.

        object refers to a metric describing a single kubernetes object (for example, hits-per-second on an Ingress object).  # noqa: E501

        :param object: The object of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :type object: IoK8sApiAutoscalingV2beta1ObjectMetricSource
        """

        self._object = object

    @property
    def pods(self) -> IoK8sApiAutoscalingV2beta1PodsMetricSource:
        """Gets the pods of this IoK8sApiAutoscalingV2beta1MetricSpec.

        pods refers to a metric describing each pod in the current scale target (for example, transactions-processed-per-second).  The values will be averaged together before being compared to the target value.  # noqa: E501

        :return: The pods of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :rtype: IoK8sApiAutoscalingV2beta1PodsMetricSource
        """
        return self._pods

    @pods.setter
    def pods(self, pods: IoK8sApiAutoscalingV2beta1PodsMetricSource):
        """Sets the pods of this IoK8sApiAutoscalingV2beta1MetricSpec.

        pods refers to a metric describing each pod in the current scale target (for example, transactions-processed-per-second).  The values will be averaged together before being compared to the target value.  # noqa: E501

        :param pods: The pods of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :type pods: IoK8sApiAutoscalingV2beta1PodsMetricSource
        """

        self._pods = pods

    @property
    def resource(self) -> IoK8sApiAutoscalingV2beta1ResourceMetricSource:
        """Gets the resource of this IoK8sApiAutoscalingV2beta1MetricSpec.

        resource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing each pod in the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.  # noqa: E501

        :return: The resource of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :rtype: IoK8sApiAutoscalingV2beta1ResourceMetricSource
        """
        return self._resource

    @resource.setter
    def resource(self, resource: IoK8sApiAutoscalingV2beta1ResourceMetricSource):
        """Sets the resource of this IoK8sApiAutoscalingV2beta1MetricSpec.

        resource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing each pod in the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.  # noqa: E501

        :param resource: The resource of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :type resource: IoK8sApiAutoscalingV2beta1ResourceMetricSource
        """

        self._resource = resource

    @property
    def type(self) -> str:
        """Gets the type of this IoK8sApiAutoscalingV2beta1MetricSpec.

        type is the type of metric source.  It should be one of \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object.  # noqa: E501

        :return: The type of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this IoK8sApiAutoscalingV2beta1MetricSpec.

        type is the type of metric source.  It should be one of \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object.  # noqa: E501

        :param type: The type of this IoK8sApiAutoscalingV2beta1MetricSpec.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
