# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiAutoscalingV2beta1ExternalMetricStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, current_average_value: IoK8sApimachineryPkgApiResourceQuantity=None, current_value: IoK8sApimachineryPkgApiResourceQuantity=None, metric_name: str=None, metric_selector: IoK8sApimachineryPkgApisMetaV1LabelSelector=None):  # noqa: E501
        """IoK8sApiAutoscalingV2beta1ExternalMetricStatus - a model defined in Swagger

        :param current_average_value: The current_average_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.  # noqa: E501
        :type current_average_value: IoK8sApimachineryPkgApiResourceQuantity
        :param current_value: The current_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.  # noqa: E501
        :type current_value: IoK8sApimachineryPkgApiResourceQuantity
        :param metric_name: The metric_name of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.  # noqa: E501
        :type metric_name: str
        :param metric_selector: The metric_selector of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.  # noqa: E501
        :type metric_selector: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """
        self.swagger_types = {
            'current_average_value': IoK8sApimachineryPkgApiResourceQuantity,
            'current_value': IoK8sApimachineryPkgApiResourceQuantity,
            'metric_name': str,
            'metric_selector': IoK8sApimachineryPkgApisMetaV1LabelSelector
        }

        self.attribute_map = {
            'current_average_value': 'currentAverageValue',
            'current_value': 'currentValue',
            'metric_name': 'metricName',
            'metric_selector': 'metricSelector'
        }

        self._current_average_value = current_average_value
        self._current_value = current_value
        self._metric_name = metric_name
        self._metric_selector = metric_selector

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiAutoscalingV2beta1ExternalMetricStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.autoscaling.v2beta1.ExternalMetricStatus of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.  # noqa: E501
        :rtype: IoK8sApiAutoscalingV2beta1ExternalMetricStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_average_value(self) -> IoK8sApimachineryPkgApiResourceQuantity:
        """Gets the current_average_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        currentAverageValue is the current value of metric averaged over autoscaled pods.  # noqa: E501

        :return: The current_average_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :rtype: IoK8sApimachineryPkgApiResourceQuantity
        """
        return self._current_average_value

    @current_average_value.setter
    def current_average_value(self, current_average_value: IoK8sApimachineryPkgApiResourceQuantity):
        """Sets the current_average_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        currentAverageValue is the current value of metric averaged over autoscaled pods.  # noqa: E501

        :param current_average_value: The current_average_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :type current_average_value: IoK8sApimachineryPkgApiResourceQuantity
        """

        self._current_average_value = current_average_value

    @property
    def current_value(self) -> IoK8sApimachineryPkgApiResourceQuantity:
        """Gets the current_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        currentValue is the current value of the metric (as a quantity)  # noqa: E501

        :return: The current_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :rtype: IoK8sApimachineryPkgApiResourceQuantity
        """
        return self._current_value

    @current_value.setter
    def current_value(self, current_value: IoK8sApimachineryPkgApiResourceQuantity):
        """Sets the current_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        currentValue is the current value of the metric (as a quantity)  # noqa: E501

        :param current_value: The current_value of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :type current_value: IoK8sApimachineryPkgApiResourceQuantity
        """
        if current_value is None:
            raise ValueError("Invalid value for `current_value`, must not be `None`")  # noqa: E501

        self._current_value = current_value

    @property
    def metric_name(self) -> str:
        """Gets the metric_name of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        metricName is the name of a metric used for autoscaling in metric system.  # noqa: E501

        :return: The metric_name of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :rtype: str
        """
        return self._metric_name

    @metric_name.setter
    def metric_name(self, metric_name: str):
        """Sets the metric_name of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        metricName is the name of a metric used for autoscaling in metric system.  # noqa: E501

        :param metric_name: The metric_name of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :type metric_name: str
        """
        if metric_name is None:
            raise ValueError("Invalid value for `metric_name`, must not be `None`")  # noqa: E501

        self._metric_name = metric_name

    @property
    def metric_selector(self) -> IoK8sApimachineryPkgApisMetaV1LabelSelector:
        """Gets the metric_selector of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        metricSelector is used to identify a specific time series within a given metric.  # noqa: E501

        :return: The metric_selector of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :rtype: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """
        return self._metric_selector

    @metric_selector.setter
    def metric_selector(self, metric_selector: IoK8sApimachineryPkgApisMetaV1LabelSelector):
        """Sets the metric_selector of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.

        metricSelector is used to identify a specific time series within a given metric.  # noqa: E501

        :param metric_selector: The metric_selector of this IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
        :type metric_selector: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """

        self._metric_selector = metric_selector
