# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1DaemonEndpoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, port: int=None):  # noqa: E501
        """IoK8sApiCoreV1DaemonEndpoint - a model defined in Swagger

        :param port: The port of this IoK8sApiCoreV1DaemonEndpoint.  # noqa: E501
        :type port: int
        """
        self.swagger_types = {
            'port': int
        }

        self.attribute_map = {
            'port': 'Port'
        }

        self._port = port

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1DaemonEndpoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.DaemonEndpoint of this IoK8sApiCoreV1DaemonEndpoint.  # noqa: E501
        :rtype: IoK8sApiCoreV1DaemonEndpoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def port(self) -> int:
        """Gets the port of this IoK8sApiCoreV1DaemonEndpoint.

        Port number of the given endpoint.  # noqa: E501

        :return: The port of this IoK8sApiCoreV1DaemonEndpoint.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port: int):
        """Sets the port of this IoK8sApiCoreV1DaemonEndpoint.

        Port number of the given endpoint.  # noqa: E501

        :param port: The port of this IoK8sApiCoreV1DaemonEndpoint.
        :type port: int
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port
