# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiAppsV1beta1RollbackConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, revision: int=None):  # noqa: E501
        """IoK8sApiAppsV1beta1RollbackConfig - a model defined in Swagger

        :param revision: The revision of this IoK8sApiAppsV1beta1RollbackConfig.  # noqa: E501
        :type revision: int
        """
        self.swagger_types = {
            'revision': int
        }

        self.attribute_map = {
            'revision': 'revision'
        }

        self._revision = revision

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiAppsV1beta1RollbackConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.apps.v1beta1.RollbackConfig of this IoK8sApiAppsV1beta1RollbackConfig.  # noqa: E501
        :rtype: IoK8sApiAppsV1beta1RollbackConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def revision(self) -> int:
        """Gets the revision of this IoK8sApiAppsV1beta1RollbackConfig.

        The revision to rollback to. If set to 0, rollback to the last revision.  # noqa: E501

        :return: The revision of this IoK8sApiAppsV1beta1RollbackConfig.
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision: int):
        """Sets the revision of this IoK8sApiAppsV1beta1RollbackConfig.

        The revision to rollback to. If set to 0, rollback to the last revision.  # noqa: E501

        :param revision: The revision of this IoK8sApiAppsV1beta1RollbackConfig.
        :type revision: int
        """

        self._revision = revision
