# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, conditions: List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition]=None, current_metrics: List[IoK8sApiAutoscalingV2beta1MetricStatus]=None, current_replicas: int=None, desired_replicas: int=None, last_scale_time: IoK8sApimachineryPkgApisMetaV1Time=None, observed_generation: int=None):  # noqa: E501
        """IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus - a model defined in Swagger

        :param conditions: The conditions of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :type conditions: List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition]
        :param current_metrics: The current_metrics of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :type current_metrics: List[IoK8sApiAutoscalingV2beta1MetricStatus]
        :param current_replicas: The current_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :type current_replicas: int
        :param desired_replicas: The desired_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :type desired_replicas: int
        :param last_scale_time: The last_scale_time of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :type last_scale_time: IoK8sApimachineryPkgApisMetaV1Time
        :param observed_generation: The observed_generation of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :type observed_generation: int
        """
        self.swagger_types = {
            'conditions': List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition],
            'current_metrics': List[IoK8sApiAutoscalingV2beta1MetricStatus],
            'current_replicas': int,
            'desired_replicas': int,
            'last_scale_time': IoK8sApimachineryPkgApisMetaV1Time,
            'observed_generation': int
        }

        self.attribute_map = {
            'conditions': 'conditions',
            'current_metrics': 'currentMetrics',
            'current_replicas': 'currentReplicas',
            'desired_replicas': 'desiredReplicas',
            'last_scale_time': 'lastScaleTime',
            'observed_generation': 'observedGeneration'
        }

        self._conditions = conditions
        self._current_metrics = current_metrics
        self._current_replicas = current_replicas
        self._desired_replicas = desired_replicas
        self._last_scale_time = last_scale_time
        self._observed_generation = observed_generation

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerStatus of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.  # noqa: E501
        :rtype: IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def conditions(self) -> List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition]:
        """Gets the conditions of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        conditions is the set of conditions required for this autoscaler to scale its target, and indicates whether or not those conditions are met.  # noqa: E501

        :return: The conditions of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :rtype: List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions: List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition]):
        """Sets the conditions of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        conditions is the set of conditions required for this autoscaler to scale its target, and indicates whether or not those conditions are met.  # noqa: E501

        :param conditions: The conditions of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :type conditions: List[IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition]
        """
        if conditions is None:
            raise ValueError("Invalid value for `conditions`, must not be `None`")  # noqa: E501

        self._conditions = conditions

    @property
    def current_metrics(self) -> List[IoK8sApiAutoscalingV2beta1MetricStatus]:
        """Gets the current_metrics of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        currentMetrics is the last read state of the metrics used by this autoscaler.  # noqa: E501

        :return: The current_metrics of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :rtype: List[IoK8sApiAutoscalingV2beta1MetricStatus]
        """
        return self._current_metrics

    @current_metrics.setter
    def current_metrics(self, current_metrics: List[IoK8sApiAutoscalingV2beta1MetricStatus]):
        """Sets the current_metrics of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        currentMetrics is the last read state of the metrics used by this autoscaler.  # noqa: E501

        :param current_metrics: The current_metrics of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :type current_metrics: List[IoK8sApiAutoscalingV2beta1MetricStatus]
        """

        self._current_metrics = current_metrics

    @property
    def current_replicas(self) -> int:
        """Gets the current_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.  # noqa: E501

        :return: The current_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._current_replicas

    @current_replicas.setter
    def current_replicas(self, current_replicas: int):
        """Sets the current_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.  # noqa: E501

        :param current_replicas: The current_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :type current_replicas: int
        """
        if current_replicas is None:
            raise ValueError("Invalid value for `current_replicas`, must not be `None`")  # noqa: E501

        self._current_replicas = current_replicas

    @property
    def desired_replicas(self) -> int:
        """Gets the desired_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.  # noqa: E501

        :return: The desired_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._desired_replicas

    @desired_replicas.setter
    def desired_replicas(self, desired_replicas: int):
        """Sets the desired_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.  # noqa: E501

        :param desired_replicas: The desired_replicas of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :type desired_replicas: int
        """
        if desired_replicas is None:
            raise ValueError("Invalid value for `desired_replicas`, must not be `None`")  # noqa: E501

        self._desired_replicas = desired_replicas

    @property
    def last_scale_time(self) -> IoK8sApimachineryPkgApisMetaV1Time:
        """Gets the last_scale_time of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods, used by the autoscaler to control how often the number of pods is changed.  # noqa: E501

        :return: The last_scale_time of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._last_scale_time

    @last_scale_time.setter
    def last_scale_time(self, last_scale_time: IoK8sApimachineryPkgApisMetaV1Time):
        """Sets the last_scale_time of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods, used by the autoscaler to control how often the number of pods is changed.  # noqa: E501

        :param last_scale_time: The last_scale_time of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :type last_scale_time: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._last_scale_time = last_scale_time

    @property
    def observed_generation(self) -> int:
        """Gets the observed_generation of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        observedGeneration is the most recent generation observed by this autoscaler.  # noqa: E501

        :return: The observed_generation of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._observed_generation

    @observed_generation.setter
    def observed_generation(self, observed_generation: int):
        """Sets the observed_generation of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.

        observedGeneration is the most recent generation observed by this autoscaler.  # noqa: E501

        :param observed_generation: The observed_generation of this IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerStatus.
        :type observed_generation: int
        """

        self._observed_generation = observed_generation
