# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1ClientIPConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timeout_seconds: int=None):  # noqa: E501
        """IoK8sApiCoreV1ClientIPConfig - a model defined in Swagger

        :param timeout_seconds: The timeout_seconds of this IoK8sApiCoreV1ClientIPConfig.  # noqa: E501
        :type timeout_seconds: int
        """
        self.swagger_types = {
            'timeout_seconds': int
        }

        self.attribute_map = {
            'timeout_seconds': 'timeoutSeconds'
        }

        self._timeout_seconds = timeout_seconds

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1ClientIPConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.ClientIPConfig of this IoK8sApiCoreV1ClientIPConfig.  # noqa: E501
        :rtype: IoK8sApiCoreV1ClientIPConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timeout_seconds(self) -> int:
        """Gets the timeout_seconds of this IoK8sApiCoreV1ClientIPConfig.

        timeoutSeconds specifies the seconds of ClientIP type session sticky time. The value must be >0 && <=86400(for 1 day) if ServiceAffinity == \"ClientIP\". Default value is 10800(for 3 hours).  # noqa: E501

        :return: The timeout_seconds of this IoK8sApiCoreV1ClientIPConfig.
        :rtype: int
        """
        return self._timeout_seconds

    @timeout_seconds.setter
    def timeout_seconds(self, timeout_seconds: int):
        """Sets the timeout_seconds of this IoK8sApiCoreV1ClientIPConfig.

        timeoutSeconds specifies the seconds of ClientIP type session sticky time. The value must be >0 && <=86400(for 1 day) if ServiceAffinity == \"ClientIP\". Default value is 10800(for 3 hours).  # noqa: E501

        :param timeout_seconds: The timeout_seconds of this IoK8sApiCoreV1ClientIPConfig.
        :type timeout_seconds: int
        """

        self._timeout_seconds = timeout_seconds
