# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiBatchV1beta1CronJobStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, active: List[IoK8sApiCoreV1ObjectReference]=None, last_schedule_time: IoK8sApimachineryPkgApisMetaV1Time=None):  # noqa: E501
        """IoK8sApiBatchV1beta1CronJobStatus - a model defined in Swagger

        :param active: The active of this IoK8sApiBatchV1beta1CronJobStatus.  # noqa: E501
        :type active: List[IoK8sApiCoreV1ObjectReference]
        :param last_schedule_time: The last_schedule_time of this IoK8sApiBatchV1beta1CronJobStatus.  # noqa: E501
        :type last_schedule_time: IoK8sApimachineryPkgApisMetaV1Time
        """
        self.swagger_types = {
            'active': List[IoK8sApiCoreV1ObjectReference],
            'last_schedule_time': IoK8sApimachineryPkgApisMetaV1Time
        }

        self.attribute_map = {
            'active': 'active',
            'last_schedule_time': 'lastScheduleTime'
        }

        self._active = active
        self._last_schedule_time = last_schedule_time

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiBatchV1beta1CronJobStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.batch.v1beta1.CronJobStatus of this IoK8sApiBatchV1beta1CronJobStatus.  # noqa: E501
        :rtype: IoK8sApiBatchV1beta1CronJobStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def active(self) -> List[IoK8sApiCoreV1ObjectReference]:
        """Gets the active of this IoK8sApiBatchV1beta1CronJobStatus.

        A list of pointers to currently running jobs.  # noqa: E501

        :return: The active of this IoK8sApiBatchV1beta1CronJobStatus.
        :rtype: List[IoK8sApiCoreV1ObjectReference]
        """
        return self._active

    @active.setter
    def active(self, active: List[IoK8sApiCoreV1ObjectReference]):
        """Sets the active of this IoK8sApiBatchV1beta1CronJobStatus.

        A list of pointers to currently running jobs.  # noqa: E501

        :param active: The active of this IoK8sApiBatchV1beta1CronJobStatus.
        :type active: List[IoK8sApiCoreV1ObjectReference]
        """

        self._active = active

    @property
    def last_schedule_time(self) -> IoK8sApimachineryPkgApisMetaV1Time:
        """Gets the last_schedule_time of this IoK8sApiBatchV1beta1CronJobStatus.

        Information when was the last time the job was successfully scheduled.  # noqa: E501

        :return: The last_schedule_time of this IoK8sApiBatchV1beta1CronJobStatus.
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._last_schedule_time

    @last_schedule_time.setter
    def last_schedule_time(self, last_schedule_time: IoK8sApimachineryPkgApisMetaV1Time):
        """Sets the last_schedule_time of this IoK8sApiBatchV1beta1CronJobStatus.

        Information when was the last time the job was successfully scheduled.  # noqa: E501

        :param last_schedule_time: The last_schedule_time of this IoK8sApiBatchV1beta1CronJobStatus.
        :type last_schedule_time: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._last_schedule_time = last_schedule_time
