# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiAuthenticationV1BoundObjectReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, api_version: str=None, kind: str=None, name: str=None, uid: str=None):  # noqa: E501
        """IoK8sApiAuthenticationV1BoundObjectReference - a model defined in Swagger

        :param api_version: The api_version of this IoK8sApiAuthenticationV1BoundObjectReference.  # noqa: E501
        :type api_version: str
        :param kind: The kind of this IoK8sApiAuthenticationV1BoundObjectReference.  # noqa: E501
        :type kind: str
        :param name: The name of this IoK8sApiAuthenticationV1BoundObjectReference.  # noqa: E501
        :type name: str
        :param uid: The uid of this IoK8sApiAuthenticationV1BoundObjectReference.  # noqa: E501
        :type uid: str
        """
        self.swagger_types = {
            'api_version': str,
            'kind': str,
            'name': str,
            'uid': str
        }

        self.attribute_map = {
            'api_version': 'apiVersion',
            'kind': 'kind',
            'name': 'name',
            'uid': 'uid'
        }

        self._api_version = api_version
        self._kind = kind
        self._name = name
        self._uid = uid

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiAuthenticationV1BoundObjectReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.authentication.v1.BoundObjectReference of this IoK8sApiAuthenticationV1BoundObjectReference.  # noqa: E501
        :rtype: IoK8sApiAuthenticationV1BoundObjectReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_version(self) -> str:
        """Gets the api_version of this IoK8sApiAuthenticationV1BoundObjectReference.

        API version of the referent.  # noqa: E501

        :return: The api_version of this IoK8sApiAuthenticationV1BoundObjectReference.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this IoK8sApiAuthenticationV1BoundObjectReference.

        API version of the referent.  # noqa: E501

        :param api_version: The api_version of this IoK8sApiAuthenticationV1BoundObjectReference.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def kind(self) -> str:
        """Gets the kind of this IoK8sApiAuthenticationV1BoundObjectReference.

        Kind of the referent. Valid kinds are 'Pod' and 'Secret'.  # noqa: E501

        :return: The kind of this IoK8sApiAuthenticationV1BoundObjectReference.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this IoK8sApiAuthenticationV1BoundObjectReference.

        Kind of the referent. Valid kinds are 'Pod' and 'Secret'.  # noqa: E501

        :param kind: The kind of this IoK8sApiAuthenticationV1BoundObjectReference.
        :type kind: str
        """

        self._kind = kind

    @property
    def name(self) -> str:
        """Gets the name of this IoK8sApiAuthenticationV1BoundObjectReference.

        Name of the referent.  # noqa: E501

        :return: The name of this IoK8sApiAuthenticationV1BoundObjectReference.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IoK8sApiAuthenticationV1BoundObjectReference.

        Name of the referent.  # noqa: E501

        :param name: The name of this IoK8sApiAuthenticationV1BoundObjectReference.
        :type name: str
        """

        self._name = name

    @property
    def uid(self) -> str:
        """Gets the uid of this IoK8sApiAuthenticationV1BoundObjectReference.

        UID of the referent.  # noqa: E501

        :return: The uid of this IoK8sApiAuthenticationV1BoundObjectReference.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this IoK8sApiAuthenticationV1BoundObjectReference.

        UID of the referent.  # noqa: E501

        :param uid: The uid of this IoK8sApiAuthenticationV1BoundObjectReference.
        :type uid: str
        """

        self._uid = uid
