# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None):  # noqa: E501
        """IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference - a model defined in Swagger

        :param name: The name of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'name': str
        }

        self.attribute_map = {
            'name': 'name'
        }

        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.flowcontrol.v1alpha1.PriorityLevelConfigurationReference of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference.  # noqa: E501
        :rtype: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference.

        `name` is the name of the priority level configuration being referenced Required.  # noqa: E501

        :return: The name of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference.

        `name` is the name of the priority level configuration being referenced Required.  # noqa: E501

        :param name: The name of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationReference.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
