# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1VolumeNodeAffinity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, required: IoK8sApiCoreV1NodeSelector=None):  # noqa: E501
        """IoK8sApiCoreV1VolumeNodeAffinity - a model defined in Swagger

        :param required: The required of this IoK8sApiCoreV1VolumeNodeAffinity.  # noqa: E501
        :type required: IoK8sApiCoreV1NodeSelector
        """
        self.swagger_types = {
            'required': IoK8sApiCoreV1NodeSelector
        }

        self.attribute_map = {
            'required': 'required'
        }

        self._required = required

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1VolumeNodeAffinity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.VolumeNodeAffinity of this IoK8sApiCoreV1VolumeNodeAffinity.  # noqa: E501
        :rtype: IoK8sApiCoreV1VolumeNodeAffinity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def required(self) -> IoK8sApiCoreV1NodeSelector:
        """Gets the required of this IoK8sApiCoreV1VolumeNodeAffinity.

        Required specifies hard node constraints that must be met.  # noqa: E501

        :return: The required of this IoK8sApiCoreV1VolumeNodeAffinity.
        :rtype: IoK8sApiCoreV1NodeSelector
        """
        return self._required

    @required.setter
    def required(self, required: IoK8sApiCoreV1NodeSelector):
        """Sets the required of this IoK8sApiCoreV1VolumeNodeAffinity.

        Required specifies hard node constraints that must be met.  # noqa: E501

        :param required: The required of this IoK8sApiCoreV1VolumeNodeAffinity.
        :type required: IoK8sApiCoreV1NodeSelector
        """

        self._required = required
