# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiAutoscalingV2beta1ResourceMetricSource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, target_average_utilization: int=None, target_average_value: IoK8sApimachineryPkgApiResourceQuantity=None):  # noqa: E501
        """IoK8sApiAutoscalingV2beta1ResourceMetricSource - a model defined in Swagger

        :param name: The name of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.  # noqa: E501
        :type name: str
        :param target_average_utilization: The target_average_utilization of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.  # noqa: E501
        :type target_average_utilization: int
        :param target_average_value: The target_average_value of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.  # noqa: E501
        :type target_average_value: IoK8sApimachineryPkgApiResourceQuantity
        """
        self.swagger_types = {
            'name': str,
            'target_average_utilization': int,
            'target_average_value': IoK8sApimachineryPkgApiResourceQuantity
        }

        self.attribute_map = {
            'name': 'name',
            'target_average_utilization': 'targetAverageUtilization',
            'target_average_value': 'targetAverageValue'
        }

        self._name = name
        self._target_average_utilization = target_average_utilization
        self._target_average_value = target_average_value

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiAutoscalingV2beta1ResourceMetricSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.autoscaling.v2beta1.ResourceMetricSource of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.  # noqa: E501
        :rtype: IoK8sApiAutoscalingV2beta1ResourceMetricSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.

        name is the name of the resource in question.  # noqa: E501

        :return: The name of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.

        name is the name of the resource in question.  # noqa: E501

        :param name: The name of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def target_average_utilization(self) -> int:
        """Gets the target_average_utilization of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.

        targetAverageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.  # noqa: E501

        :return: The target_average_utilization of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.
        :rtype: int
        """
        return self._target_average_utilization

    @target_average_utilization.setter
    def target_average_utilization(self, target_average_utilization: int):
        """Sets the target_average_utilization of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.

        targetAverageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.  # noqa: E501

        :param target_average_utilization: The target_average_utilization of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.
        :type target_average_utilization: int
        """

        self._target_average_utilization = target_average_utilization

    @property
    def target_average_value(self) -> IoK8sApimachineryPkgApiResourceQuantity:
        """Gets the target_average_value of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.

        targetAverageValue is the target value of the average of the resource metric across all relevant pods, as a raw value (instead of as a percentage of the request), similar to the \"pods\" metric source type.  # noqa: E501

        :return: The target_average_value of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.
        :rtype: IoK8sApimachineryPkgApiResourceQuantity
        """
        return self._target_average_value

    @target_average_value.setter
    def target_average_value(self, target_average_value: IoK8sApimachineryPkgApiResourceQuantity):
        """Sets the target_average_value of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.

        targetAverageValue is the target value of the average of the resource metric across all relevant pods, as a raw value (instead of as a percentage of the request), similar to the \"pods\" metric source type.  # noqa: E501

        :param target_average_value: The target_average_value of this IoK8sApiAutoscalingV2beta1ResourceMetricSource.
        :type target_average_value: IoK8sApimachineryPkgApiResourceQuantity
        """

        self._target_average_value = target_average_value
