# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, api_version: str=None, kind: str=None, metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta=None, spec: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec=None, status: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus=None):  # noqa: E501
        """IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration - a model defined in Swagger

        :param api_version: The api_version of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.  # noqa: E501
        :type api_version: str
        :param kind: The kind of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.  # noqa: E501
        :type kind: str
        :param metadata: The metadata of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.  # noqa: E501
        :type metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        :param spec: The spec of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.  # noqa: E501
        :type spec: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec
        :param status: The status of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.  # noqa: E501
        :type status: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus
        """
        self.swagger_types = {
            'api_version': str,
            'kind': str,
            'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMeta,
            'spec': IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec,
            'status': IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus
        }

        self.attribute_map = {
            'api_version': 'apiVersion',
            'kind': 'kind',
            'metadata': 'metadata',
            'spec': 'spec',
            'status': 'status'
        }

        self._api_version = api_version
        self._kind = kind
        self._metadata = metadata
        self._spec = spec
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.flowcontrol.v1alpha1.PriorityLevelConfiguration of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.  # noqa: E501
        :rtype: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_version(self) -> str:
        """Gets the api_version of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources  # noqa: E501

        :return: The api_version of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources  # noqa: E501

        :param api_version: The api_version of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def kind(self) -> str:
        """Gets the kind of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds  # noqa: E501

        :return: The kind of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds  # noqa: E501

        :param kind: The kind of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :type kind: str
        """

        self._kind = kind

    @property
    def metadata(self) -> IoK8sApimachineryPkgApisMetaV1ObjectMeta:
        """Gets the metadata of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        `metadata` is the standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata  # noqa: E501

        :return: The metadata of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :rtype: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta):
        """Sets the metadata of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        `metadata` is the standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata  # noqa: E501

        :param metadata: The metadata of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :type metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta
        """

        self._metadata = metadata

    @property
    def spec(self) -> IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec:
        """Gets the spec of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        `spec` is the specification of the desired behavior of a \"request-priority\". More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status  # noqa: E501

        :return: The spec of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :rtype: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec):
        """Sets the spec of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        `spec` is the specification of the desired behavior of a \"request-priority\". More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status  # noqa: E501

        :param spec: The spec of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :type spec: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationSpec
        """

        self._spec = spec

    @property
    def status(self) -> IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus:
        """Gets the status of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        `status` is the current status of a \"request-priority\". More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status  # noqa: E501

        :return: The status of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :rtype: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus
        """
        return self._status

    @status.setter
    def status(self, status: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus):
        """Sets the status of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.

        `status` is the current status of a \"request-priority\". More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status  # noqa: E501

        :param status: The status of this IoK8sApiFlowcontrolV1alpha1PriorityLevelConfiguration.
        :type status: IoK8sApiFlowcontrolV1alpha1PriorityLevelConfigurationStatus
        """

        self._status = status
