# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1NodeSelectorRequirement(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, key: str=None, operator: str=None, values: List[str]=None):  # noqa: E501
        """IoK8sApiCoreV1NodeSelectorRequirement - a model defined in Swagger

        :param key: The key of this IoK8sApiCoreV1NodeSelectorRequirement.  # noqa: E501
        :type key: str
        :param operator: The operator of this IoK8sApiCoreV1NodeSelectorRequirement.  # noqa: E501
        :type operator: str
        :param values: The values of this IoK8sApiCoreV1NodeSelectorRequirement.  # noqa: E501
        :type values: List[str]
        """
        self.swagger_types = {
            'key': str,
            'operator': str,
            'values': List[str]
        }

        self.attribute_map = {
            'key': 'key',
            'operator': 'operator',
            'values': 'values'
        }

        self._key = key
        self._operator = operator
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1NodeSelectorRequirement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.NodeSelectorRequirement of this IoK8sApiCoreV1NodeSelectorRequirement.  # noqa: E501
        :rtype: IoK8sApiCoreV1NodeSelectorRequirement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this IoK8sApiCoreV1NodeSelectorRequirement.

        The label key that the selector applies to.  # noqa: E501

        :return: The key of this IoK8sApiCoreV1NodeSelectorRequirement.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this IoK8sApiCoreV1NodeSelectorRequirement.

        The label key that the selector applies to.  # noqa: E501

        :param key: The key of this IoK8sApiCoreV1NodeSelectorRequirement.
        :type key: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def operator(self) -> str:
        """Gets the operator of this IoK8sApiCoreV1NodeSelectorRequirement.

        Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.  # noqa: E501

        :return: The operator of this IoK8sApiCoreV1NodeSelectorRequirement.
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator: str):
        """Sets the operator of this IoK8sApiCoreV1NodeSelectorRequirement.

        Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.  # noqa: E501

        :param operator: The operator of this IoK8sApiCoreV1NodeSelectorRequirement.
        :type operator: str
        """
        if operator is None:
            raise ValueError("Invalid value for `operator`, must not be `None`")  # noqa: E501

        self._operator = operator

    @property
    def values(self) -> List[str]:
        """Gets the values of this IoK8sApiCoreV1NodeSelectorRequirement.

        An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.  # noqa: E501

        :return: The values of this IoK8sApiCoreV1NodeSelectorRequirement.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values: List[str]):
        """Sets the values of this IoK8sApiCoreV1NodeSelectorRequirement.

        An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.  # noqa: E501

        :param values: The values of this IoK8sApiCoreV1NodeSelectorRequirement.
        :type values: List[str]
        """

        self._values = values
