# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoK8sApiCoreV1ObjectFieldSelector(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, api_version: str=None, field_path: str=None):  # noqa: E501
        """IoK8sApiCoreV1ObjectFieldSelector - a model defined in Swagger

        :param api_version: The api_version of this IoK8sApiCoreV1ObjectFieldSelector.  # noqa: E501
        :type api_version: str
        :param field_path: The field_path of this IoK8sApiCoreV1ObjectFieldSelector.  # noqa: E501
        :type field_path: str
        """
        self.swagger_types = {
            'api_version': str,
            'field_path': str
        }

        self.attribute_map = {
            'api_version': 'apiVersion',
            'field_path': 'fieldPath'
        }

        self._api_version = api_version
        self._field_path = field_path

    @classmethod
    def from_dict(cls, dikt) -> 'IoK8sApiCoreV1ObjectFieldSelector':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io.k8s.api.core.v1.ObjectFieldSelector of this IoK8sApiCoreV1ObjectFieldSelector.  # noqa: E501
        :rtype: IoK8sApiCoreV1ObjectFieldSelector
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_version(self) -> str:
        """Gets the api_version of this IoK8sApiCoreV1ObjectFieldSelector.

        Version of the schema the FieldPath is written in terms of, defaults to \"v1\".  # noqa: E501

        :return: The api_version of this IoK8sApiCoreV1ObjectFieldSelector.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this IoK8sApiCoreV1ObjectFieldSelector.

        Version of the schema the FieldPath is written in terms of, defaults to \"v1\".  # noqa: E501

        :param api_version: The api_version of this IoK8sApiCoreV1ObjectFieldSelector.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def field_path(self) -> str:
        """Gets the field_path of this IoK8sApiCoreV1ObjectFieldSelector.

        Path of the field to select in the specified API version.  # noqa: E501

        :return: The field_path of this IoK8sApiCoreV1ObjectFieldSelector.
        :rtype: str
        """
        return self._field_path

    @field_path.setter
    def field_path(self, field_path: str):
        """Sets the field_path of this IoK8sApiCoreV1ObjectFieldSelector.

        Path of the field to select in the specified API version.  # noqa: E501

        :param field_path: The field_path of this IoK8sApiCoreV1ObjectFieldSelector.
        :type field_path: str
        """
        if field_path is None:
            raise ValueError("Invalid value for `field_path`, must not be `None`")  # noqa: E501

        self._field_path = field_path
